spring.application.name=wrapper-xml-json

server.port=${SERVER_PORT:8081}

#Endpoint = "https://run.mocky.io/v3/19217075-6d4e-4818-98bc-416d1feb7b84"
Endpoint=${ENDPOINT_URL:https://acme-test.free.beeceptor.com/sent-order}

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always